# Generated by Django 3.1.4 on 2020-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucrt', models.CharField(max_length=5, verbose_name='Ücret')),
                ('ucrt_title', models.CharField(max_length=5, verbose_name='Title')),
            ],
        ),
    ]
