# Generated by Django 3.1.4 on 2020-12-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_paket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paket',
        ),
    ]
