# Generated by Django 3.1.4 on 2020-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paket_ucrt', models.CharField(max_length=5, verbose_name='Paket Ücreti')),
                ('paket_title', models.CharField(max_length=25, verbose_name='Paket Başlığı')),
                ('paket_1', models.CharField(max_length=25, verbose_name='Paket Özelliği 1')),
                ('paket_2', models.CharField(max_length=25, verbose_name='Paket Özelliği 2')),
                ('paket_3', models.CharField(max_length=25, verbose_name='Paket Özelliği 3')),
                ('paket_4', models.CharField(max_length=25, verbose_name='Paket Özelliği 4')),
                ('paket_5', models.CharField(max_length=25, verbose_name='Paket Özelliği 5')),
                ('paket_6', models.CharField(max_length=25, verbose_name='Paket Özelliği 6')),
                ('paket_7', models.CharField(max_length=25, verbose_name='Paket Özelliği 7')),
                ('paket_8', models.CharField(max_length=25, verbose_name='Paket Özelliği 8')),
                ('paket_9', models.CharField(max_length=25, verbose_name='Paket Özelliği 9')),
            ],
        ),
    ]
